[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "https://pgropwfkdcvbccdgscff.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBncm9wd2ZrZGN2YmNjZGdzY2ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MjU0OTcsImV4cCI6MjA1NzIwMTQ5N30.Zbf0U4PH4m5_ieSmzhxX2isHdZCP7OB_FxUF2exW9rM"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"